import {
  index,
  integer,
  primaryKey,
  sqliteTable,
  text,
  uniqueIndex,
} from 'drizzle-orm/sqlite-core';
import { user } from './auth-schema';

/**
 * Sort-cost note (BE-04, Phase 5).
 *
 * Apex is single-user, expected ≤5k rows per user. Sorting by
 * `hoursPlayed`, `genre`, or `status` performs an in-memory sort after a
 * filtered scan (no covering index). Measured at ~10ms on local WAL DB
 * with 5k rows — acceptable while the model continues to evolve.
 * Adding indices is deferred until the schema stabilises; premature
 * indices on fields likely to be reshaped cost a migrate-add + migrate-drop
 * round trip with no user benefit. See feedback_no_premature_indices.
 *
 * Already indexed: title, platform, format, releaseYear (each scoped by
 * (user_id, kind, ...)).
 */
export const games = sqliteTable(
  'games',
  {
    id: integer('id').primaryKey({ autoIncrement: true }),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    kind: text('kind').notNull().default('owned'),
    title: text('title').notNull(),
    developer: text('developer'),
    genre: text('genre').notNull(),
    releaseYear: integer('release_year'),
    platform: text('platform').notNull(),
    edition: text('edition'),
    hoursPlayed: integer('hours_played'),
    status: text('status'),
    format: text('format').notNull().default('digital'),
    coverColor: text('cover_color'),
    coverImage: text('cover_image'),
    price: integer('price'),
    purchasedAt: text('purchased_at'),
    notes: text('notes'),
    metadataProvider: text('metadata_provider'),
    metadataProviderId: text('metadata_provider_id'),
    metadataMatchedAt: text('metadata_matched_at'),
    externalId: text('external_id').notNull(),
    createdAt: integer('created_at', { mode: 'timestamp' }).$defaultFn(() => new Date()),
    updatedAt: integer('updated_at', { mode: 'timestamp' })
      .$defaultFn(() => new Date())
      .$onUpdateFn(() => new Date()),
  },
  (table) => [
    index('games_user_id_idx').on(table.userId),
    uniqueIndex('games_user_id_external_id_unq').on(table.userId, table.externalId),
    index('games_user_kind_idx').on(table.userId, table.kind),
    index('games_user_kind_platform_idx').on(table.userId, table.kind, table.platform),
    index('games_user_kind_format_idx').on(table.userId, table.kind, table.format),
    index('games_user_kind_releaseyear_idx').on(table.userId, table.kind, table.releaseYear),
    index('games_user_kind_title_idx').on(table.userId, table.kind, table.title),
  ],
);

export type GameRow = typeof games.$inferSelect;
export type NewGameRow = typeof games.$inferInsert;

/**
 * Shape consumed by `toGameInsertRow`. Optional fields map to NULL columns.
 * Discriminated by `kind` so the shape mirrors the domain split between
 * 'owned' and 'wishlist'. New columns added here MUST also be wired into
 * `toGameInsertRow` — that's the single edit point three INSERT call-sites
 * (DrizzleGameRepository.create, applyMerge, applyReplace) pivot on.
 */
export type GameRowInput = {
  kind: 'owned' | 'wishlist';
  externalId: string;
  title: string;
  genre: string;
  platform: string;
  format: string;
  developer?: string | null;
  releaseYear?: { value: number } | number | null;
  edition?: string | null;
  hoursPlayed?: { value: number } | number | null;
  status?: string | null;
  coverColor?: string | null;
  coverImage?: string | null;
  price?: { value: number } | number | null;
  purchasedAt?: { value: string } | string | null;
  notes?: string | null;
  metadataRef?: { providerName: string; providerId: string; matchedAt: Date } | null;
};

/**
 * Build a `NewGameRow` from a domain-agnostic input shape. Single edit point
 * for the three INSERT call-sites (BE-02). Unwraps value-object wrappers
 * (`{ value }`) and coalesces all nullable columns to explicit `null` so
 * Drizzle inserts predictable rows. Does not set id/createdAt/updatedAt —
 * those are auto-generated by the schema.
 */
export function toGameInsertRow(userId: string, input: GameRowInput): NewGameRow {
  const unwrap = <T>(v: { value: T } | T | null | undefined): T | null => {
    if (v == null) return null;
    if (typeof v === 'object' && 'value' in (v as object)) {
      return (v as { value: T }).value;
    }
    return v as T;
  };
  return {
    userId,
    externalId: input.externalId,
    kind: input.kind,
    title: input.title,
    developer: input.developer ?? null,
    genre: input.genre,
    releaseYear: unwrap(input.releaseYear),
    platform: input.platform,
    edition: input.edition ?? null,
    hoursPlayed: unwrap(input.hoursPlayed),
    status: input.status ?? null,
    format: input.format,
    coverColor: input.coverColor ?? null,
    coverImage: input.coverImage ?? null,
    price: unwrap(input.price),
    purchasedAt: unwrap(input.purchasedAt),
    notes: input.notes ?? null,
    metadataProvider: input.metadataRef?.providerName ?? null,
    metadataProviderId: input.metadataRef?.providerId ?? null,
    metadataMatchedAt: input.metadataRef?.matchedAt.toISOString() ?? null,
  };
}

export const platforms = sqliteTable(
  'platforms',
  {
    id: integer('id').primaryKey({ autoIncrement: true }),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    externalId: text('external_id').notNull(),
    createdAt: integer('created_at', { mode: 'timestamp' }).$defaultFn(() => new Date()),
  },
  (table) => [
    index('platforms_user_id_idx').on(table.userId),
    uniqueIndex('platforms_user_id_name_unq').on(table.userId, table.name),
    uniqueIndex('platforms_user_id_external_id_unq').on(table.userId, table.externalId),
  ],
);

export type PlatformRow = typeof platforms.$inferSelect;
export type NewPlatformRow = typeof platforms.$inferInsert;

export const genres = sqliteTable(
  'genres',
  {
    id: integer('id').primaryKey({ autoIncrement: true }),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    externalId: text('external_id').notNull(),
    createdAt: integer('created_at', { mode: 'timestamp' }).$defaultFn(() => new Date()),
  },
  (table) => [
    index('genres_user_id_idx').on(table.userId),
    uniqueIndex('genres_user_id_name_unq').on(table.userId, table.name),
    uniqueIndex('genres_user_id_external_id_unq').on(table.userId, table.externalId),
  ],
);

export type GenreRow = typeof genres.$inferSelect;
export type NewGenreRow = typeof genres.$inferInsert;

export const developers = sqliteTable(
  'developers',
  {
    id: integer('id').primaryKey({ autoIncrement: true }),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    externalId: text('external_id').notNull(),
    createdAt: integer('created_at', { mode: 'timestamp' }).$defaultFn(() => new Date()),
  },
  (table) => [
    index('developers_user_id_idx').on(table.userId),
    uniqueIndex('developers_user_id_name_unq').on(table.userId, table.name),
    uniqueIndex('developers_user_id_external_id_unq').on(table.userId, table.externalId),
  ],
);

export type DeveloperRow = typeof developers.$inferSelect;
export type NewDeveloperRow = typeof developers.$inferInsert;

export const metadataCache = sqliteTable(
  'metadata_cache',
  {
    id: integer('id').primaryKey({ autoIncrement: true }),
    provider: text('provider').notNull(),
    cacheKey: text('cache_key').notNull(),
    candidatesJson: text('candidates_json').notNull(),
    fetchedAt: integer('fetched_at', { mode: 'timestamp' }).notNull(),
  },
  (table) => [
    uniqueIndex('metadata_cache_provider_cache_key_unq').on(table.provider, table.cacheKey),
  ],
);

export type MetadataCacheRow = typeof metadataCache.$inferSelect;
export type NewMetadataCacheRow = typeof metadataCache.$inferInsert;


/**
 * Distributed advisory lock for cron jobs (single-region, SQLite-based).
 * `locked_until` is unix epoch seconds — see CronLock for the UPSERT pattern.
 */
export const cronLocks = sqliteTable('cron_locks', {
  name: text('name').primaryKey(),
  lockedUntil: integer('locked_until').notNull(),
  owner: text('owner').notNull(),
});

export type CronLockRow = typeof cronLocks.$inferSelect;
export type NewCronLockRow = typeof cronLocks.$inferInsert;

/**
 * Idempotency-Key cache for mutating endpoints (RFC: Idempotency-Key header).
 *
 * Composite PRIMARY KEY (key, user_id) scopes uniqueness per-user so two
 * different accounts can independently reuse the same client-generated key
 * without colliding. Only 2xx responses are stored — 5xx must remain
 * retryable. `request_hash` lets us detect "same key, different body" and
 * answer with a 409 conflict per Stripe's convention.
 *
 * `created_at` (unix epoch ms) is indexed so the cleanup cron can prune rows
 * older than the configured TTL in a single index-scan.
 */
export const idempotencyKeys = sqliteTable(
  'idempotency_keys',
  {
    key: text('key').notNull(),
    userId: text('user_id').notNull(),
    requestHash: text('request_hash').notNull(),
    status: integer('status').notNull(),
    responseBody: text('response_body').notNull(),
    createdAt: integer('created_at').notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.key, table.userId] }),
    index('idempotency_keys_created_at_idx').on(table.createdAt),
  ],
);

export type IdempotencyKeyRow = typeof idempotencyKeys.$inferSelect;
export type NewIdempotencyKeyRow = typeof idempotencyKeys.$inferInsert;

/**
 * Per-user credentials for third-party integrations (IGDB and future
 * providers). `client_id` is plaintext (it is not a secret in the IGDB OAuth2
 * client-credentials flow); `client_secret_ciphertext` is base64 of
 * `iv ‖ ciphertext ‖ authTag` produced by Aes256GcmCipher. The unique index
 * enforces one row per user per integration kind.
 */
export const integrationCredentials = sqliteTable(
  'integration_credentials',
  {
    id: text('id').primaryKey(),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    integration: text('integration').notNull(),
    enabled: integer('enabled', { mode: 'boolean' }).notNull().default(false),
    clientId: text('client_id').notNull(),
    clientSecretCiphertext: text('client_secret_ciphertext').notNull(),
    lastVerifiedAt: integer('last_verified_at', { mode: 'timestamp_ms' }),
    createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
    updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull(),
  },
  (table) => [
    uniqueIndex('integration_credentials_user_integration_unique').on(
      table.userId,
      table.integration,
    ),
  ],
);

export type IntegrationCredentialRow = typeof integrationCredentials.$inferSelect;
export type NewIntegrationCredentialRow = typeof integrationCredentials.$inferInsert;

/**
 * Per-user cached OAuth bearer token for an external integration. Composite
 * primary key `(user_id, integration)` so each user's Twitch app-access token
 * is isolated from every other user's. Row lifetime is fully machine-managed
 * (rotated by IgdbTokenStore on expiry). Cascade-deletes with the parent
 * `integration_credentials` row through the shared `user_id` FK.
 */
export const integrationOauthToken = sqliteTable(
  'integration_oauth_token',
  {
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    integration: text('integration').notNull(),
    accessToken: text('access_token').notNull(),
    expiresAt: integer('expires_at', { mode: 'timestamp' }).notNull(),
    obtainedAt: integer('obtained_at', { mode: 'timestamp' }).notNull(),
  },
  (table) => [primaryKey({ columns: [table.userId, table.integration] })],
);

export type IntegrationOauthTokenRow = typeof integrationOauthToken.$inferSelect;
export type NewIntegrationOauthTokenRow = typeof integrationOauthToken.$inferInsert;

/**
 * Per-user fixed-window mutation rate-limit buckets.
 *
 * Composite PRIMARY KEY `(user_id, window_start)` enables atomic
 * `INSERT … ON CONFLICT DO UPDATE SET count = count + 1` to increment
 * the per-window counter without a read-modify-write race.
 *
 * `window_start` is a unix epoch in **milliseconds**, aligned to the
 * window size (currently 60_000ms — see `mutation-rate-limit.ts`).
 * The secondary index supports the cron sweep that prunes expired
 * buckets via `DELETE WHERE window_start < cutoff`.
 */
export const rateLimitBuckets = sqliteTable(
  'rate_limit_buckets',
  {
    userId: text('user_id').notNull(),
    windowStart: integer('window_start').notNull(),
    count: integer('count').notNull().default(0),
  },
  (table) => [
    primaryKey({ columns: [table.userId, table.windowStart] }),
    index('rate_limit_buckets_window_start_idx').on(table.windowStart),
  ],
);

export type RateLimitBucketRow = typeof rateLimitBuckets.$inferSelect;
export type NewRateLimitBucketRow = typeof rateLimitBuckets.$inferInsert;
